from bpmn_dmn.dmn import DMNDecisionRunner

#runner = DMNDecisionRunner('string_integer_decision.dmn', debug='DEBUG')
runner = DMNDecisionRunner('./Rules/string_integer_decision.dmn')
res = runner.decide('m', 30)
print(res.description)
res = runner.decide('m', 24)
print(res.description)
res = runner.decide('m', 45)
print(res.description)
res = runner.decide('f', 25)
print(res.description)
res = runner.decide('f', 14)
print(res.description)
res = runner.decide('f', 45)
print(res.description)
res = runner.decide('', 0)
print(res.description)
res = runner.decide('x', 8)
print(res.description)
res = runner.decide('x', 45)
print(res.description)