@startuml
'!pragma useVerticalIf on
scale 1.5
start
if (Age < 1) then (yes)
    -[#green]->
    #palegreen:NB;
elseif (Age <= 10) then (yes)
    -[#green]->
    #palegreen:Child;
elseif (Gender m) then (yes)
    -[#green]->
    if (Age 30) then (yes)
        -[#green]->
        #palegreen:30;
    elseif (Age < 25) then (yes)
        -[#green]->
        #palegreen:mLow;
    else (other)
        -[#green,dotted]->
        #palegreen:mHigh;
    endif
elseif (Gender f) then (yes)
    -[#green]->
    if (Age 25) then (yes)
        -[#green]->
        #palegreen:25;
    elseif (Age < 20) then (yes)
        -[#green]->
        #palegreen:fLow;
    else (other)
        -[#green,dotted]->
        #palegreen:fHigh;
    endif
else (other)
    -[#red,dotted]->
    #pink:else;
endif
stop
@enduml