Memory:

      +--------+
   0  |        |  <- start
      +--------+
   1  |        |  <- q  scans from start to end
      +--------+
      :  ..... |
      +--------+
      |        |  <- end
      +--------+  <-+
      |        |    |
      +--------+    | rest of the
      :  ..... |    | allocated memory
      +--------+    |
  n   |        |    |
      +--------+  <-+


Strings:


    0               n
   +--+=----+--+--+--+
   |  | ... |  |  |\0|
   +--+-----+--+--+--+
     ^        ^
     |        |
     |        +-- q moves from the
     |            end to the start
     p moves from
       start to the end


Sectioned:

   +------+----+----+----+----+----+----+
   | xxxx | yy | zz | 00 | tt | 11 | ss |
   +------+----+----+----+----+----+----+
    ^      ^    ^    ^    ^    ^    ^ 
    |      |    |    |    |    |    |
    |      |    |    |    |    |    +--- storage registry
    |      |    |    |    |    +-------- always set to 1
    |      |    |    |    +------------- temp value
    |      |    |    +------------------ always zeroed 
    |      |    +----------------------- zero flag value
    |      +---------------------------- y register
    +----------------------------------- x address