@startuml
ditaa

    +--------+   +-------+    +-------+
    |        | --+ ditaa +--> |       |
    |  Text  |   +-------+    |diagram|
    |Document|   |!magic!|    |       |
    |     {d}|   |       |    |       |
    +---+----+   +-------+    +-------+
        :                         ^
        |       Lots of work      |
        +-------------------------+

+---------+
| cBLU    |
|         |
|    +----+
|    |cPNK|
|    |    |
+----+----+

Rounded Corners:

/--+
|  |
+--/

Tags:

+-----+
|{d}  |
|     |
|     |
+-----+

+-----+
|{s}  |
|     |
|     |
+-----+

+-----+
|{io} |
|     |
|     |
+-----+

Dashed Lines:

+----+
:    |
|{s} |
+----+

/----\ 
|    | 
|    | 
\-=--+ 

----+
    :
    |
    v

Point Markers:

*----*
|    |
*    *
|    |
*----*

    /--*
    |
-*--+

*    /--->
|    |
|    |
\----/

@enduml