@startuml
ditaa

Memory:

      +--------+
   0  | cGRE   |  <-- start
      +--------+
   1  | cYEL   |  <-- q  scans from start to end
      +--------+
      :  ..... |
      +--------+
      | cRED   |  <-- end
      +--------+  
      |        |  <-+
      +--------+    | rest of the
      :  ..... |    | allocated memory
      +--------+    |
   n  |        |  <-+
      +--------+  

Strings:

    0               n
   +--+=----+--+--+--+
   |  | ... |  |  |\0|
   +--+-----+--+--+--+
     ^        ^
     |        |
     |        +-- q moves from the
     |            end to the start
     p moves from
       start to the end



    0  1  2  3  4
   +--+--+--+--+--+
   |C |A |S |A |\0|
   +--+--+--+--+--+

Sectioned:

   +------+----+----+----+----+----+----+
   | xxxx | yy | zz | 00 | tt | 11 | ss |
   +------+----+----+----+----+----+----+
    ^      ^    ^    ^    ^    ^    ^ 
    |      |    |    |    |    |    |
    |      |    |    |    |    |    +--- storage registry
    |      |    |    |    |    +-------- always set to 1
    |      |    |    |    +------------- temp value
    |      |    |    +------------------ always zeroed 
    |      |    +----------------------- zero flag value
    |      +---------------------------- y register
    +----------------------------------- x address

/--------+
|        |
|        |
\--------+

/-|Clientes|------------\ 
|                       |
+---+-------------------+
|   |                   :
+---+-------------------+
*   |                   *
:   |                   |
+---+---------+---------+
|             |         |
+-------------+---------+
|                       |
|                       |
\-----------------------/

/-----------------------\ 
| cBLU                  |
| Uma mensagem!         |
|                       |
|               /-=----\|
|               |  Ok  ||
|               \------/|
\-----------------------/

*-----*
|     |
*     *
*-----*

+---------------------------------------------------+
| *ola                                              |
| **mundo                                           |
| ***de                                             |
| ****novo                                          |
|                                                   |
| o um                                              |
| o dois                                            |
+---------------------------------------------------+

@enduml