@startsalt
'skinparam BackgroundColor lightblue
scale 1.5
{+
    |area1|area2|area3|area4|area5|area6|area7
    |.|{* File | Edit | Source | ?
    '  File | New | Open File | - | Close | Close All | - | Exit
      ? | About}|*|*|*|*
    |.
    |.|{/ <b>General | Fullscreen | Behavior | Saving }|*|*|*|*
    |.
    |.|Login    |"MyName          "|.
    |.|Password |"****            "|.
    |.
    |.|Open image in|{| ^Smart Mode^ }|{^Options
                                        [X] Smooth images when zoomed
                                        [X] Confirm image deletion
                                        [ ] Show hidden images
                                       }
    |.|Sexo|{(X) Masculino
             () Feminino}
    |.
    |.|Estado|{SI 
                Acre
                Amapa
                Amazonas
              }|{^Privacy | (X) public | () default | () private} |*|*
    |.
    |.|{#
        .     | Column 2  | Column 3 | Column 4 | Column 5
        Row 1 | value 1   | value 2  | value 3  | value 4
        Row 2 | long cell | *        | *        | *
       }|*|*|{T
              + World
              ++ Europe
              +++ Italy
              +++ Germany
              ++++ Berlin
              ++ Africa
             }|*
    |.
    |.|.|.|.|[  OK<&account-login>   ]|[Cancel<&circle-x>]
    |.
}
@endsalt
