@startuml
ditaa
/-|Clientes|-----------------------------------------------------------------------------------------------------------------------------\ 
|                                                                                                                                        |
|                                                                                                                                        |
|            +-------------+                                                                                                             |
| ID         | cAAA00000041|                                                                                                             |
|            +-------------+                                                                                                             |
|            +------------------------------------------------------------------+                                                        |
| Nome       |Giovani Perotto Mesquita                                          |                                                        |
|            +------------------------------------------------------------------+                                                        |
|            +----------------------------------------------------------------------------+                                              |
| Logradouro |Rua Pelotas, 443 apto 33                                                    |                                              |
|            +----------------------------------------------------------------------------+                                              |
|            +---------+        +----------------------+        +-------------------------+                                              |
| CEP        |90220-110| Bairro |Floresta              | Cidade |Porto Alegre             |                                              |
|            +---------+        +----------------------+        +-------------------------+                                              |
|            +---------------+                                                                                                           |
| CIC        |62256092020    |                                                                                                           |
|            +---------------+                                                                                                           |
|                                                                                                                                        |
|     +------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
|     |Pedido|Item    |Data |Valor  |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
||cAAA|      |        |     |       |                                                                                                   ||
|+----+------+--------+-----+-------+---------------------------------------------------------------------------------------------------+|
|                                                                                                            /----------\  /----------\  |
|                                                                                                            |cAAAOk    |  |  Cancel  |  |
|                                                                                                            \----------/  \----------/  |
\----------------------------------------------------------------------------------------------------------------------------------------/
@enduml