@startuml

!pragma teoz true
'skinparam backgroundColor #EEEBDC
'skinparam handwritten true
autonumber "<b>[00]"
skinparam style strictuml
skinparam roundcorner 20
skinparam sequenceParticipant underline
skinparam maxMessageSize 200

skinparam sequence{
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF
    
    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor #A9DCDF
    
    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

Title "Rest Full"
Footer "GiovaniPM\n01/02/2021"

actor User as U
box "Scope"
    participant "Client" as A
    participant "Application Server" as B
    participant "Datasource" as C
end box
database Oracle as O

== Load Data ==

U -> A: Acess Browse
activate A

{q1} A -> B: HTTP GET
activate B

B -> C: HTTP GET
activate C

C -> O: Select

hnote over C: idle

O -> C: Commit

C --> B: JSON Response
deactivate C

{q2} B --> A: JSON Response
deactivate B

== User Maintance ==

group User Revision

    A --> U: Visualization
    activate A

    hnote over A: idle

    U --> U: Changes

    U --> A: Confirmation
    deactivate A
    
end

== Save Data ==

{q3} A -> B: HTTP PUT
activate B

B -> C: HTTP PUT
activate C

C -> O: Update

hnote over C: idle

O -> C: Commit

C --> B: Success Response
deactivate C

{q4} B --> A: Success Response
deactivate B

A -> U: Done
deactivate A

{q1} <-> {q2} : <color #red>Response Time</color>
{q3} <-> {q4} : <color #red>Response Time</color>

@enduml