@startuml
'skinparam backgroundColor #EEEBDC
'skinparam handwritten true
autonumber "<b>[000]"

skinparam sequence{
    ArrowColor DeepSkyBlue
    ActorBorderColor DeepSkyBlue
    LifeLineBorderColor blue
    LifeLineBackgroundColor #A9DCDF
    
    ParticipantBorderColor DeepSkyBlue
    ParticipantBackgroundColor DodgerBlue
    ParticipantFontName Impact
    ParticipantFontSize 17
    ParticipantFontColor #A9DCDF
    
    ActorBackgroundColor aqua
    ActorFontColor DeepSkyBlue
    ActorFontSize 17
    ActorFontName Aapex
}

actor User as U
participant "Client" as A
participant "Application Server" as B
participant "Datasource" as C

U -> A: Acess Browse
activate A

A -> B: HTTP GET
activate B

B -> C: HTTP GET
activate C

C --> B: JSON Response
deactivate C

B --> A: JSON Response
deactivate B

group User Revision

    A --> U: Visualization
    activate A

    U --> U: Changes

    U --> A: Confirmation
    deactivate A
    
end

A -> B: HTTP PUT
activate B

B -> C: HTTP PUT
activate C

C --> B: Success Response
deactivate C

B --> A: Success Response
deactivate B

A --> U: Done
deactivate A
@enduml